### ISSUE TITLE
Should run .prepareForDeferredProcessing on events not to lose MDC info

### ISSUE THREAD

**Issue by holyjak** [dibog/cloudwatch-logback-appender#1]
According to https://logback.qos.ch/apidocs/ch/qos/logback/classic/spi/LoggingEvent.html#prepareForDeferredProcessing():

> It should also be called when using asynchronous or deferred logging. 

That should be done likely in `io.github.dibog.AwsLogAppender#append` before adding it to the queue for later, async processing. That way data from `org.slf4j.MDC` will not be lost.

**Comment by dibog** [comment]
Cool. Would you mind to create a pull request for that, with a test or demo demonstrating it.

**Comment by holyjak** [comment]
Will try.

**Comment by holyjak** [comment]
Any questions? Or anything else to do before this can be merged and release? I would love having it out :)

**Comment by dibog** [comment]
Hi Holyjak, 
no, I have currently no questions. I'm currently a bit busy and was not able to have a look. I planned to do it this weekend. Would that be okay or would that be too late?

**Comment by holyjak** [comment]
That's OK, thanks a lot!
