### ISSUE TITLE
streamName should contain instance specific prefix

### ISSUE THREAD

**Issue by adrianbn** [dibog/cloudwatch-logback-appender#5]
Different instances can't share the same log stream and log group in Cloudwatch. When using an autoscaling group or otherwise deploying multiple instances of the same service, the streamName will collide and cause issues. 

A possible solution is for the streamName to be prepended by the instance ID or allow some sort of interpolation on the logback.xml file to do so both in the stream name and the layout pattern.

**Comment by dibog** [comment]
Hi @adrianbn 

Great idea. That is already possible. Please have a look here: 
https://github.com/dibog/cloudwatch-logback-appender/blob/master/README.md#-unique-log-stream-names

**Comment by adrianbn** [comment]
Hi @dibog , 

Thanks for the answer. That's interesting, but still requires some configuration management process (cloud-init, chef, etc) to get in and modify the startup script with a runtime -D parameter. It's not much different than modifying logback.xml via cloud-init to replace the streamName entry. 

What would be interesting is if the library got the instance ID from the metadata URL on startup and used it as part of the streamName. Maybe allowing the user to specify some sort of interpolation `<streamName>%id-myapp</streamName>`. That would simplify deployment.
