### ISSUE TITLE
Unable to debug issue

### ISSUE THREAD

**Issue by sk3674** [dibog/cloudwatch-logback-appender#6]
I am adding the appender to an application that logs to the File without issue. When I added this appender to point to a dev AWS Cloudwatch account, everything worked fine. But when I config it against our production account, the application fails to startup. The only exception I get from the tomcat log is: 
Caused by: java.lang.NullPointerException
        at io.github.dibog.AwsLogAppender.stop(AwsLogAppender.java:95)

Is there any way I can see why the appender is failing? 
This is what my appender looks like:

```
......

appender("cloud-watch", AwsLogAppender){
    awsConfig(AwsConfig){
        credentials(AwsCredentials){
            accessKeyId = "xxxxxxx"
            secretAccessKey = "xxxxxxxxx"
        }
        region = "eu-west-1"
    }


    createLogGroup = false
    queueLength = 100
    groupName = "test-group"
    streamName = "test"
    dateFormat = "yyyyMMdd_HHmmss"
    layout(PatternLayout) {
        pattern = "[%X{currentID}] %-5level %logger{35} - %msg %n"
    }

}


logger("com.abc.def", INFO, ["FILE", "cloud-watch"])
root(WARN, ["FILE", "cloud-watch"])

```

**Comment by dibog** [comment]
Hi @sk3674.

can you tell me which version of  cloudwatch-logback-appender are you using?

Best regards,
Dieter

**Comment by sk3674** [comment]
I am using version 1.0.3. The issue is with the "logger" definition. 
When I create the logger as below, the application runs without issue:
logger("com.abc.def", INFO, ["FILE"])
root(WARN, ["FILE", "cloud-watch"])

But as soon as I use the "cloud-watch" appender in the logger definition, the application fails to start:
logger("com.abc.def", INFO, ["FILE", "cloud-watch"])
root(WARN, ["FILE", "cloud-watch"])

**Comment by dibog** [comment]
Hi @sk3674,

I see where you get the NullPointerException happens and I protect against it.
It seems that the stop method of the appender is called more then once and now the call is idempotent.
I will add to this issue as soon as I can release a new version.

**Comment by dibog** [comment]
The following release

`<dependency>
  <groupId>io.github.dibog</groupId>
  <artifactId>cloudwatch-logback-appender</artifactId>
  <version>1.0.5</version>
</dependency>`

should avoid the NullPointerException. Please reopen this issue if it is still present.
