### ISSUE TITLE
What is meaning behind warning message "Skipped 14 messages in the last log cycle."?

### ISSUE THREAD

**Issue by valters** [dibog/cloudwatch-logback-appender#8]
Hi,

I received following message from the logger:
```
07:44:12 07:44:12.731 WARN AWS Cloud Watch Logger - Skipped 14 messages in the last log cycle.
```
It is unclear what this actually means. a) Does it mean that it dropped 14 messages (was unable to upload to them to CloudWatch)? b) Does it mean that 14 messages were lost because they were overwritten in RingBuffer, before they could be picked up by appender?

If (b), was it because the RingBuffer capacity of 10 items too small? (The program might be writing a lot of logs, and CW struggling to keep up?)
 Would increasing the ring buffer size make this less likely to happen?

To me, it seems "skipped" does not really explain what happened to those log messages.

In general, what can I do about it? I don't want any log messages to disappear, ideally 100% of what I log needs to end up in CW logs.

**Comment by dibog** [comment]
Hi @valters,

it means b): the messages were overwritten within the ring buffer. You can increase the buffer. Increasing will help if there is a burst of log message. 

With the next release the log message is hinting to the readme.

**Comment by dibog** [comment]
The following release should contain the info:
<dependency>
  <groupId>io.github.dibog</groupId>
  <artifactId>cloudwatch-logback-appender</artifactId>
  <version>1.0.5</version>
</dependency>

**Comment by valters** [comment]
Hi Dieter,
The ring buffer seems to be initialized here: https://github.com/dibog/cloudwatch-logback-appender/blob/master/src/main/java/io/github/dibog/AwsCWEventDump.java#L33 with hardcoded value of 10. 

I am not sure if I can follow if "queueLength" is ever used to increase ring buffer size. I will try to review. Thank you for updating the log message!

**Comment by valters** [comment]
After review I decided to submit pull request #9 to address my concern...
